### ISSUE TITLE
WebHID & Go!Motion

### ISSUE THREAD

**Issue by murkle** [VernierSoftwareTechnology/GoIO_SDK#5]
I've got the Go!Temp working nicely in Chrome using the new WebHID protocol, see https://murkle.github.io/utils/webhid/gotemp.html

I'd like to do the same for the Go!Motion - it works if I initialise it using the official app (ie once it starts clicking it works fine with WebHID)

Please can you help me figure out how to initialise it over WebHID?

**Comment by stocktonkincade** [comment]
@murkle, that sounds like some pretty nifty progress. We are loving WebHID.

The Go!Motion requires an additional parameter structure in the Init command.  If you look in the source for the [GoIO_Sensor_Open()](https://github.com/VernierST/GoIO_SDK/blob/4bd9d650c22036a77b666cebd4f3b1051b699d28/src/GoIO_DLL/GoIO_DLL_interface.cpp#L567) function, you can see that the Go!Motion gets the additional (GCyclopsInitParams) structure passed to the SKIP_CMD_ID_INIT command. This really just sets a flag to tell the Go!Motion to behave better with a low-power host, like a calculator. [Here is the GCyclopsInitParams structure definition](https://github.com/VernierST/GoIO_SDK/blob/4bd9d650c22036a77b666cebd4f3b1051b699d28/src/GoIO_cpp/GCyclopsCommExt.h#L81).

I think that this is what you are missing in your WebHID implementation. Let us know if you have other questions.

**Comment by murkle** [comment]
Thanks, so if I've understood correctly I need to send this, is that right?
SKIP_CMD_ID_INIT, 1, 2
ie 
0x1a, 1, 2

or possibly SKIP_CMD_ID_START_MEASUREMENTS = 0x18 instead.

How does that need to be sent? Is there any header format like on Go Direct? (eg 1 byte length + 4 byte header)

**Comment by stocktonkincade** [comment]
@murkle, I grabbed your html and did a little modification to make sure that it works. Note that I did not bother handling errors, timeouts, command responses. So, it is just a brute force demonstration of the basic command set.

Here is that [gist](https://gist.github.com/stocktonkincade/a348e7048fcae76ccdec656985210770).

**Comment by murkle** [comment]
Thanks so much - that's awesome!

**Comment by stocktonkincade** [comment]
@murkle, you should also explore our WebHID/WebBluetooth solution for Go Direct devices. The communication library is [here](https://github.com/VernierST/godirect-js) and some extensive examples are [here](https://github.com/VernierST/godirect-examples/tree/main/javascript).
